### ISSUE TITLE
Error when building a project with obfustring-plugin.

### ISSUE THREAD

**Issue by RE4ERKA** [c0nnor263/obfustring-plugin#3]
Gradle JVM: 17.0.8

build.gradle:
```
buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle-api:8.2.0"
        classpath "com.android.tools.build:gradle:8.2.0"
        classpath "io.github.c0nnor263:obfustring-plugin:12.0.0"
    }
}

plugins {
    id 'java'
    id 'io.github.c0nnor263.obfustring-plugin'
}

repositories {
    mavenCentral()
}

group 'me.re4erka'
version '1.0-SNAPSHOT'
```

Error:
https://pastebin.com/GAVPGSTw

**Comment by c0nnor263** [comment]
Hello!
Based on the error, it looks like you missed installing some repository sources.
`org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'io.github.c0nnor263.obfustring-plugin'] was not found in any of the following sources`

I can advise you to indicate one of the missing ones like the following:

```
repositories {
    mavenCentral()
    gradlePluginPortal()    // Add this line
}
```


Also, you should remember that the `obfustring-plugin` is currently only available for Android gradle modules, regardless of project - Android app or library, etc. Be sure to apply your plugins in this order:

```
plugins {
    id("com.android.application")    // Required for the obfuscation-plugin to work
    id("io.github.c0nnor263.obfustring-plugin")
}
```


Sorry for the problem with the `obfustring-plugin`. I'm going to add this repository source to the documentation

Can you confirm that your issue has been resolved?

**Comment by RE4ERKA** [comment]
I tried adding the "com.android.application" plugin, but that also caused an error. I hope I did it right.

build.gradle:
```
buildscript {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle-api:8.2.0"
        classpath "com.android.tools.build:gradle:8.2.0"
        classpath "io.github.c0nnor263:obfustring-plugin:12.0.0"
    }
}

plugins {
    id 'java'
    id 'com.android.application'
    id 'io.github.c0nnor263.obfustring-plugin'
}

repositories {
    mavenCentral()
    gradlePluginPortal()
    maven { url 'https://jitpack.io' }
}

group 'me.re4erka'
version '1.0-SNAPSHOT'
```

Error:
https://pastebin.com/WyPqwccx
