### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TonDevv** [c0nnor263/obfustring-plugin#4]
i got this error : 
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'ObfustringMode' for extension 'obfustring' of type io.github.c0nnor263.obfustringplugin.ObfustringExtension.
i used : 
classpath("io.github.c0nnor263:obfustring-plugin:12.0.1")

id 'io.github.c0nnor263.obfustring-plugin'

obfustring {
    /**
     * Key used to obfuscate strings
     */
    key = "werwer88"

    /**
     * Configure obfustring mode using [ObfustringMode]
     */
    mode = ObfustringMode.DEFAULT

    /**
     * Enable logging
     */
    loggingEnabled = true

    /**
     * Set JVM argument -Xstring-concat using [StringConcatStrategy]
     */
    stringConcatStrategy = StringConcatStrategy.INDY
}

**Comment by c0nnor263** [comment]
Could you please provide the contents of the app and project modules build.gradle, settings.gradle files?
